import { z } from "zod";
import { asBoolean } from "./lib/json.js";

const envSchema = z.object({
  PORT: z.string().default("8080"),
  TRUST_PROXY_HOPS: z.string().default("1"),
  RATE_WINDOW_MS: z.string().default("60000"),
  RATE_MAX: z.string().default("120"),
  REQUEST_TIMEOUT_MS: z.string().default("15000"),
  AUTH_REQUIRED: z.string().default("true"),
  EXECUTOR_MODE: z.enum(["dry_run", "terraform_cloud", "local_terraform"]).default("dry_run"),
  INTERNAL_TOKEN: z.string().default(""),
  INTERNAL_TOKEN_VAULT_PATH: z.string().default("secret/data/platform-deploy-service"),
  INTERNAL_TOKEN_VAULT_KEY: z.string().default("token"),
  GITHUB_API_BASE: z.string().default("https://api.github.com"),
  GITHUB_AUTH_MODE: z.enum(["auto", "token", "github_app"]).default("auto"),
  GITHUB_TOKEN: z.string().default(""),
  GITHUB_TOKEN_VAULT_PATH: z.string().default("secret/data/platform-deploy-service/github"),
  GITHUB_TOKEN_VAULT_KEYS: z.string().default("token,github_token,github-token"),
  GITHUB_APP_ID: z.string().default(""),
  GITHUB_APP_ID_VAULT_PATH: z.string().default("secret/data/platform-deploy-service/github"),
  GITHUB_APP_ID_VAULT_KEYS: z.string().default("app_id,github_app_id,github-app-id"),
  GITHUB_APP_INSTALLATION_ID: z.string().default(""),
  GITHUB_APP_INSTALLATION_ID_VAULT_PATH: z.string().default("secret/data/platform-deploy-service/github"),
  GITHUB_APP_INSTALLATION_ID_VAULT_KEYS: z.string().default("installation_id,github_app_installation_id,github-app-installation-id"),
  GITHUB_APP_PRIVATE_KEY: z.string().default(""),
  GITHUB_APP_PRIVATE_KEY_VAULT_PATH: z.string().default("secret/data/platform-deploy-service/github"),
  GITHUB_APP_PRIVATE_KEY_VAULT_KEYS: z.string().default("private_key,github_app_private_key,github-app-private-key"),
  TFE_TOKEN: z.string().default(""),
  TFE_TOKEN_VAULT_PATH: z.string().default("secret/data/platform-deploy-service"),
  TFE_TOKEN_VAULT_KEYS: z.string().default("tfe_token,tfe-token,tf_api_token"),
  TFE_AGENT_POOL_ID: z.string().default(""),
  TFE_AGENT_POOL_ID_VAULT_PATH: z.string().default("secret/data/platform-deploy-service"),
  TFE_AGENT_POOL_ID_VAULT_KEYS: z.string().default("tfe_agent_pool_id,tfe-agent-pool-id"),
  TFE_ORGANIZATION: z.string().default(""),
  TFE_ORGANIZATION_VAULT_PATH: z.string().default("secret/data/platform-deploy-service"),
  TFE_ORGANIZATION_VAULT_KEYS: z.string().default("tfe_organization,tfe-organization,tf_cloud_organization"),
  APP_AUTH_GATEWAY_ADMIN_TOKEN: z.string().default(""),
  APP_AUTH_GATEWAY_ADMIN_TOKEN_VAULT_PATH: z.string().default("secret/data/auth-gateway-admin-api"),
  APP_AUTH_GATEWAY_ADMIN_TOKEN_VAULT_KEYS: z.string().default("value"),
  CLOUDFLARE_TOKEN: z.string().default(""),
  CLOUDFLARE_TOKEN_VAULT_PATH: z.string().default("secret/data/platform-deploy-service"),
  CLOUDFLARE_TOKEN_VAULT_KEYS: z.string().default("cloudflare_token,cloudflare-token"),
  CLOUDFLARE_ACCOUNT_ID: z.string().default(""),
  CLOUDFLARE_ACCOUNT_ID_VAULT_PATH: z.string().default("secret/data/platform-deploy-service"),
  CLOUDFLARE_ACCOUNT_ID_VAULT_KEYS: z.string().default("cloudflare_account_id,cloudflare-account-id"),
  CLOUDFLARE_ZONE_ID: z.string().default(""),
  CLOUDFLARE_ZONE_ID_VAULT_PATH: z.string().default("secret/data/platform-deploy-service"),
  CLOUDFLARE_ZONE_ID_VAULT_KEYS: z.string().default("cloudflare_zone_id,cloudflare-zone-id"),
  WORKSPACE_ROOT: z.string().default("/tmp/platform-deploy-executor-workspace"),
  OPENOBSERVE_BROWSER_RUM_CACHE_DIR: z.string().default("/tmp/platform-deploy-executor-cache/openobserve-browser-rum"),
  VAULT_ADDR: z.string().default("http://vault.vault.svc.cluster.local:8200"),
  VAULT_TOKEN_FILE: z.string().default("/vault-secrets/vault-token"),
  TOKEN_CACHE_SECONDS: z.string().default("300"),
  PLATFORM_DEPLOY_SERVICE_URL: z.string().default("http://platform-deploy-service.directus.svc.cluster.local:8080"),
  PRODUCTION_DEPLOY_READY_TIMEOUT_MS: z.string().default("600000"),
  PRODUCTION_DEPLOY_READY_POLL_MS: z.string().default("2000"),
  OPENAPI_SERVER_URL: z.string().default("http://platform-deploy-executor.directus.svc.cluster.local:8080")
});

const parsed = envSchema.parse(process.env);

export const config = {
  port: Math.max(1, Math.min(65535, Number(parsed.PORT) || 8080)),
  trustProxyHops: Math.max(0, Number(parsed.TRUST_PROXY_HOPS) || 1),
  rateWindowMs: Math.max(1000, Number(parsed.RATE_WINDOW_MS) || 60_000),
  rateMax: Math.max(1, Number(parsed.RATE_MAX) || 120),
  requestTimeoutMs: Math.max(1000, Number(parsed.REQUEST_TIMEOUT_MS) || 15_000),
  authRequired: asBoolean(parsed.AUTH_REQUIRED, true),
  executorMode: parsed.EXECUTOR_MODE,
  internalToken: parsed.INTERNAL_TOKEN,
  internalTokenVaultPath: parsed.INTERNAL_TOKEN_VAULT_PATH,
  internalTokenVaultKey: parsed.INTERNAL_TOKEN_VAULT_KEY,
  githubApiBase: parsed.GITHUB_API_BASE.replace(/\/+$/, ""),
  githubAuthMode: parsed.GITHUB_AUTH_MODE,
  githubToken: parsed.GITHUB_TOKEN,
  githubTokenVaultPath: parsed.GITHUB_TOKEN_VAULT_PATH,
  githubTokenVaultKeys: parseList(parsed.GITHUB_TOKEN_VAULT_KEYS),
  githubAppId: parsed.GITHUB_APP_ID,
  githubAppIdVaultPath: parsed.GITHUB_APP_ID_VAULT_PATH,
  githubAppIdVaultKeys: parseList(parsed.GITHUB_APP_ID_VAULT_KEYS),
  githubAppInstallationId: parsed.GITHUB_APP_INSTALLATION_ID,
  githubAppInstallationIdVaultPath: parsed.GITHUB_APP_INSTALLATION_ID_VAULT_PATH,
  githubAppInstallationIdVaultKeys: parseList(parsed.GITHUB_APP_INSTALLATION_ID_VAULT_KEYS),
  githubAppPrivateKey: parsed.GITHUB_APP_PRIVATE_KEY,
  githubAppPrivateKeyVaultPath: parsed.GITHUB_APP_PRIVATE_KEY_VAULT_PATH,
  githubAppPrivateKeyVaultKeys: parseList(parsed.GITHUB_APP_PRIVATE_KEY_VAULT_KEYS),
  tfeToken: parsed.TFE_TOKEN,
  tfeTokenVaultPath: parsed.TFE_TOKEN_VAULT_PATH,
  tfeTokenVaultKeys: parseList(parsed.TFE_TOKEN_VAULT_KEYS),
  tfeAgentPoolId: parsed.TFE_AGENT_POOL_ID,
  tfeAgentPoolIdVaultPath: parsed.TFE_AGENT_POOL_ID_VAULT_PATH,
  tfeAgentPoolIdVaultKeys: parseList(parsed.TFE_AGENT_POOL_ID_VAULT_KEYS),
  tfeOrganization: parsed.TFE_ORGANIZATION,
  tfeOrganizationVaultPath: parsed.TFE_ORGANIZATION_VAULT_PATH,
  tfeOrganizationVaultKeys: parseList(parsed.TFE_ORGANIZATION_VAULT_KEYS),
  appAuthGatewayAdminToken: parsed.APP_AUTH_GATEWAY_ADMIN_TOKEN,
  appAuthGatewayAdminTokenVaultPath: parsed.APP_AUTH_GATEWAY_ADMIN_TOKEN_VAULT_PATH,
  appAuthGatewayAdminTokenVaultKeys: parseList(parsed.APP_AUTH_GATEWAY_ADMIN_TOKEN_VAULT_KEYS),
  cloudflareToken: parsed.CLOUDFLARE_TOKEN,
  cloudflareTokenVaultPath: parsed.CLOUDFLARE_TOKEN_VAULT_PATH,
  cloudflareTokenVaultKeys: parseList(parsed.CLOUDFLARE_TOKEN_VAULT_KEYS),
  cloudflareAccountId: parsed.CLOUDFLARE_ACCOUNT_ID,
  cloudflareAccountIdVaultPath: parsed.CLOUDFLARE_ACCOUNT_ID_VAULT_PATH,
  cloudflareAccountIdVaultKeys: parseList(parsed.CLOUDFLARE_ACCOUNT_ID_VAULT_KEYS),
  cloudflareZoneId: parsed.CLOUDFLARE_ZONE_ID,
  cloudflareZoneIdVaultPath: parsed.CLOUDFLARE_ZONE_ID_VAULT_PATH,
  cloudflareZoneIdVaultKeys: parseList(parsed.CLOUDFLARE_ZONE_ID_VAULT_KEYS),
  workspaceRoot: parsed.WORKSPACE_ROOT,
  openObserveBrowserRumCacheDir: parsed.OPENOBSERVE_BROWSER_RUM_CACHE_DIR,
  vaultAddr: parsed.VAULT_ADDR.replace(/\/+$/, ""),
  vaultTokenFile: parsed.VAULT_TOKEN_FILE,
  tokenCacheSeconds: Math.max(5, Number(parsed.TOKEN_CACHE_SECONDS) || 300),
  platformDeployServiceUrl: parsed.PLATFORM_DEPLOY_SERVICE_URL.replace(/\/+$/, ""),
  productionDeployReadyTimeoutMs: Math.max(60_000, Number(parsed.PRODUCTION_DEPLOY_READY_TIMEOUT_MS) || 600_000),
  productionDeployReadyPollMs: Math.max(500, Number(parsed.PRODUCTION_DEPLOY_READY_POLL_MS) || 2_000),
  openApiServerUrl: parsed.OPENAPI_SERVER_URL
};

export type ExecutorMode = typeof config.executorMode;

function parseList(value: string): string[] {
  return value.split(",").map((item) => item.trim()).filter(Boolean);
}
